=== apysk6/XML/Lab4/uczelnia.dtd
<!ENTITY % dane_personalne "tytul?, imie, nazwisko">
<!ELEMENT uczelnia   (nazwa, rektor, prorektor, prorektor,
                      wydzial+, biblioteka?)>

<!ELEMENT nazwa      (#PCDATA)>
<!ELEMENT rektor     (%dane_personalne;)>
<!ELEMENT prorektor  (%dane_personalne;)>
<!ELEMENT imie       (#PCDATA)>
<!ELEMENT nazwisko   (#PCDATA)>
<!ELEMENT tytul      (#PCDATA)>
<!ELEMENT wydzial    (nazwa, dziekan, prodziekan*, (instytut+|kierunek+))>
<!ELEMENT dziekan    (%dane_personalne;)>
<!ELEMENT prodziekan (%dane_personalne;)>
<!ELEMENT instytut   (nazwa, dyrektor, katedra*)>
<!ELEMENT dyrektor   (%dane_personalne;)>
<!ELEMENT kierunek   (#PCDATA)>
<!ELEMENT katedra    (#PCDATA)>
<!ELEMENT biblioteka  EMPTY>

=== apysk6/XML/Lab4/uczelnia.xml
<!DOCTYPE uczelnia SYSTEM "uczelnia.dtd">
<uczelnia>
<nazwa>Uniwersytet Gdanski</nazwa>
<rektor>
    <tytul>Rektor</tytul>
    <imie>Jerzy Piotr</imie>
    <nazwisko>Gwizda≈Ça </nazwisko>
</rektor>
    
<prorektor>
    <tytul>Profesor Nadzwyczajny</tytul>
    <imie>Arnold</imie>
    <nazwisko>Klonczynski</nazwisko>
</prorektor>
    
<prorektor>
    <tytul>Prof. Dr. Hab.</tytul>
    <imie></imie>
    <nazwisko></nazwisko>
</prorektor>

<wydzial>
    <nazwa>Matematyki Fizyki i Informatyki</nazwa>
    <dziekan>
        <tytul>Profesora</tytul>
        <imie>Piotr</imie>
        <nazwisko>Bojarski</nazwisko>
    </dziekan>
    
    <prodziekan>
        <tytul>Doktor</tytul>
        <imie>Barbara</imie>
        <nazwisko>Wolnik</nazwisko>
    </prodziekan>
    
    <kierunek>Informatyka</kierunek>
</wydzial>    
    
    
</uczelnia>
