=== apysk6/XML/Lab5/listastud.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="nrindeksutype">
    <xs:restriction base="xs:integer">
      <xs:pattern value="[0-9]{6}"/>
    </xs:restriction>
  </xs:simpleType>


<xs:element name="nazwisko" type="xs:string"/>
<xs:element name="imie" type="xs:string"/>
<xs:element name="nrindeksu" type="nrindeksutype"/>
<xs:element name="dataurodzenia" type="xs:date"/>
<xs:element name="sredniaocen" type="xs:float"/>
<xs:element name="stronadomowa" type="xs:anyURI"/>



<xs:element name="student">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="nazwisko"/>
      <xs:element ref="imie"/>
      <xs:element ref="nrindeksu"/>
      <xs:element ref="dataurodzenia"/>
      <xs:element ref="sredniaocen"/>
      <xs:element ref="stronadomowa"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="listastud">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="student" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


</xs:schema>

=== apysk6/XML/Lab5/listastud.xml
<?xml version="1.0"?>
<listastud xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="listastud.xsd">
	<student>
			<nazwisko>Kowalska</nazwisko>
			<imie>Anna</imie>
			<nrindeksu>301237</nrindeksu>
			<dataurodzenia>1995-02-18</dataurodzenia>
			<sredniaocen>4.45</sredniaocen>
			<stronadomowa>http://anka.kowalska.wp.pl</stronadomowa>
	</student>
	<student>
			<nazwisko>Marcinkowski</nazwisko>
			<imie>Jan</imie>
			<nrindeksu>302318</nrindeksu>
			<dataurodzenia>1995-08-23</dataurodzenia>
			<sredniaocen>4.33</sredniaocen>
			<stronadomowa>http://jannnn0001.onet.pl</stronadomowa>
	</student>
	<student>
			<nazwisko>Trybulski</nazwisko>
			<imie>Pawe≈Ç</imie>
			<nrindeksu>307319</nrindeksu>
			<dataurodzenia>1995-12-04</dataurodzenia>
			<sredniaocen>3.91</sredniaocen>
			<stronadomowa>http://trybolxxx.interia.pl</stronadomowa>
	</student>
</listastud>
